#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Запуск линтинга изменённых файлов с lint-staged..."
yarn lint-staged

echo "Запуск тестов..."
yarn test
if [ $? -ne 0 ]; then
  echo "Тесты не прошли. Отклонение коммита."
  exit 1
fi

echo "Все проверки успешно пройдены!"
